export const USER_SENT_FIRST_MESSAGE = 'USER_SENT_FIRST_MESSAGE';
export const USER_SENT_MESSAGE = 'USER_SENT_MESSAGE';
export const GET_USER_MESSAGES = 'GET_USER_MESSAGES';
export const USER_CHANGED_CURRENT_THREAD = 'USER_CHANGED_CURRENT_THREAD';
export const NEW_MESSAGE_RECEIVED_ON_CURRENT_THREAD = 'NEW_MESSAGE_RECEIVED_ON_CURRENT_THREAD';
export const NEW_MESSAGE_RECEIVED_ON_OTHER_THREAD = 'NEW_MESSAGE_RECEIVED_ON_OTHER_THREAD';