export const USER_SIGN_UP_REQUEST = 'USER_SIGN_UP_REQUEST';
export const USER_COMPLETED_SIGN_UP_REQUEST = 'USER_COMPLETED_SIGN_UP_REQUEST';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_GET_INFO_REQUEST = 'USER_GET_INFO_REQUEST';



