export const FIND_USER_MATCHES = 'FIND_USER_MATCHES';
export const FIND_INDUSTRY_MATCHES = 'FIND_INDUSTRY_MATCHES';
export const CHECKBOX_CLICKED = 'CHECKBOX_CLICKED';
export const FIND_INDUSTRY_SEARCH = 'FIND_INDUSTRY_SEARCH';
export const REMOVE_INDUSTRY_SEARCH = 'REMOVE_INDUSTRY_SEARCH';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const REINITIALIZE_SEARCH_STATE = 'REINITIALIZE_SEARCH_STATE';

